# Generated by Django 3.1.11 on 2022-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_url', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=15)),
            ],
        ),
    ]
