# Generated by Django 3.1.11 on 2021-07-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='useename',
            new_name='username',
        ),
    ]
