# Generated by Django 3.1.11 on 2021-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMAN'), ('HN', 'HINDI')], max_length=2),
        ),
    ]
