# Generated by Django 3.1.11 on 2021-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210702_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_production',
            field=models.CharField(max_length=20),
        ),
    ]
