# Generated by Django 3.2.4 on 2021-07-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='menu_images/')),
                ('price', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(related_name='item', to='customer.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='customer.MenuItem')),
            ],
        ),
    ]
