# Generated by Django 3.1.11 on 2022-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortner',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=1000)),
                ('uuid', models.CharField(max_length=10)),
            ],
        ),
    ]
